FROM python:3.8

# install openvsp only
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /usr/local
COPY generic-python3-comp/openvsp-comp/OpenVSP-3.31.1-Linux.deb /usr/local/OpenVSP.deb
RUN chmod ao+rx /usr/local/OpenVSP.deb
# WARNING: adding exit 0 to skip over  desktop-file-install: command not found error
RUN apt install /usr/local/OpenVSP.deb ; exit 0 

# setup python API
WORKDIR /
RUN mkdir /app
COPY protobufs /app/protobufs
COPY generic-python3-comp/editables/*.py /app/openvsp-comp/editables/
COPY generic-python3-comp/component.py /app/openvsp-comp/
COPY generic-python3-comp/component_api.py /app/openvsp-comp/
COPY generic-python3-comp/openvsp-comp/requirements.txt /app/openvsp-comp/
COPY generic-python3-comp/README.md /app/openvsp-comp/
COPY generic-python3-comp/VERSION /app/openvsp-comp/
COPY generic-python3-comp/LICENSE /app/openvsp-comp/

RUN chmod -R 755 /app
WORKDIR /app/openvsp-comp

RUN chmod -R 777 editables

RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/component.proto

# setup openvsp executable symbolic links
RUN python -m pip install -r requirements.txt
ARG OpenVSP_PATH="$(python -c 'from distutils. sysconfig import get_python_lib; print(get_python_lib())')/openvsp"
WORKDIR $OpenVSP_PATH
RUN ln -s /opt/OpenVSP/vspviewer && ln -s /opt/OpenVSP/vsploads && ln -s /opt/OpenVSP/vspaero
WORKDIR /app/openvsp-comp

# Create the non-root user
ARG USERNAME=non-root
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
USER $USERNAME

EXPOSE 50060
ENTRYPOINT [ "python", "-u", "component_api.py" ]