# Dockerfile for running preCICE on ubuntu 20.04
FROM precice/ci-ubuntu-2004:latest

# install preCICE and ccx adapter prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
        libarpack2-dev \
        libspooles-dev \
        libyaml-cpp-dev \
        python3-pip \
        pkg-config \
        # lsof \
        # net-tools \
        # iputils-ping \
        # vim \
  && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/precice/precice/releases/download/v2.5.0/libprecice2_2.5.0_focal.deb
RUN apt install -y --no-install-recommends ./libprecice2_2.5.0_focal.deb

# install openfoam 
RUN wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | bash
RUN apt-get install -y openfoam2212-default


# setup component folders
WORKDIR /
RUN mkdir /app
COPY generic-python3-comp/protobufs /app/protobufs
COPY generic-python3-comp/editables /app/precice-openfoam-comp/editables
COPY generic-python3-comp/precice-comp/precice.py /app/precice-openfoam-comp/
COPY generic-python3-comp/precice-comp/tools /app/precice-openfoam-comp/tools
COPY generic-python3-comp/calculix-fea-comp/calculix.py /app/precice-openfoam-comp/
COPY generic-python3-comp/component.py /app/precice-openfoam-comp/
COPY generic-python3-comp/component_api.py /app/precice-openfoam-comp/
COPY generic-python3-comp/requirements.txt /app/precice-openfoam-comp/
COPY generic-python3-comp/README.md /app/precice-openfoam-comp/
COPY generic-python3-comp/VERSION /app/precice-openfoam-comp/
COPY generic-python3-comp/LICENSE /app/precice-openfoam-comp/

RUN chmod -R 755 /app
WORKDIR /app/precice-openfoam-comp

RUN chmod -R 777 editables

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/component.proto

# get openfoam adapter
RUN wget https://github.com/precice/openfoam-adapter/archive/refs/tags/v1.2.2.tar.gz
RUN tar -xf v1.2.2.tar.gz
# The source code is now in the openfoam-adapter-1.2.2 directory 
RUN chmod -R 777 openfoam-adapter-1.2.2

# set non-root user (already created in precice ci image)
ARG USERNAME=precice
USER $USERNAME

# configure openfoam environment variables for user and user install openfoam adapter
WORKDIR /app/precice-openfoam-comp/openfoam-adapter-1.2.2
RUN ["/bin/bash", "-c" , "source /usr/lib/openfoam/openfoam2212/etc/bashrc && ./Allwmake"]

WORKDIR /app/precice-openfoam-comp

EXPOSE 50060
ENTRYPOINT [ "python", "-u", "component_api.py" ]
