FROM python:3.8

RUN mkdir /app
COPY protobufs /app/protobufs
COPY generic-python3-comp/component.py /app/generic-python3-driver/
COPY generic-python3-comp/component_api.py /app/generic-python3-driver/
COPY generic-python3-comp/requirements.txt /app/generic-python3-driver/
COPY generic-python3-comp/README.md /app/generic-python3-driver/
COPY generic-python3-comp/VERSION /app/generic-python3-driver/
COPY generic-python3-comp/LICENSE /app/generic-python3-driver/

# driver specific
COPY generic-python3-comp/driver_editables/*.py /app/generic-python3-driver/editables/
COPY generic-python3-comp/driver_editables/*.txt /app/generic-python3-driver/editables/
COPY generic-python3-comp/component_api2.py /app/generic-python3-driver/

RUN chmod -R 755 /app
WORKDIR /app/generic-python3-driver

RUN chmod -R 777 editables

RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/component.proto

# driver specific
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/orchestrator.proto
ENV ORCHESTRATOR_HOST="controller:50051"

# Create the non-root user
ARG USERNAME=non-root
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
USER $USERNAME

EXPOSE 50060
ENTRYPOINT [ "python", "-u", "component_api.py" ]