# Dockerfile for running preCICE on ubuntu 20.04
FROM precice/ci-ubuntu-2004:latest

# install preCICE and ccx adapter prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
        libarpack2-dev \
        libspooles-dev \
        libyaml-cpp-dev \
        python3-pip \
        # lsof \
        # net-tools \
        # iputils-ping \
        # vim \
  && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/precice/precice/releases/download/v2.5.0/libprecice2_2.5.0_focal.deb
RUN apt install -y --no-install-recommends ./libprecice2_2.5.0_focal.deb

# install adapter
RUN wget http://www.dhondt.de/ccx_2.20.src.tar.bz2
RUN tar xvjf ccx_2.20.src.tar.bz2  
# The source code is now in the ~/CalculiX/ccx_2.20/src directory where the adapter is looking for it
RUN wget https://github.com/precice/calculix-adapter/releases/download/v2.20.0/calculix-precice2_2.20.0-1_amd64_focal.deb
RUN apt -y --no-install-recommends install ./calculix-precice2_2.20.0-1_amd64_focal.deb


# setup component folders
WORKDIR /
RUN mkdir /app
COPY generic-python3-comp/protobufs /app/protobufs
COPY generic-python3-comp/editables /app/precice-calculix-comp/editables
COPY generic-python3-comp/precice-comp/precice.py /app/precice-calculix-comp/
COPY generic-python3-comp/calculix-fea-comp/calculix.py /app/precice-calculix-comp/
COPY generic-python3-comp/component.py /app/precice-calculix-comp/
COPY generic-python3-comp/component_api.py /app/precice-calculix-comp/
COPY generic-python3-comp/requirements.txt /app/precice-calculix-comp/
COPY generic-python3-comp/README.md /app/precice-calculix-comp/
COPY generic-python3-comp/VERSION /app/precice-calculix-comp/
COPY generic-python3-comp/LICENSE /app/precice-calculix-comp/

RUN chmod -R 755 /app
WORKDIR /app/precice-calculix-comp

RUN chmod -R 777 editables

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/component.proto

# set non-root user (already created in precice ci image)
ARG USERNAME=precice
USER $USERNAME

EXPOSE 50060
ENTRYPOINT [ "python", "-u", "component_api.py" ]
