# Dockerfile for running preCICE on ubuntu 20.04
FROM precice/ci-ubuntu-2004:latest

# install preCICE and ccx adapter prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
        libarpack2-dev \
        libspooles-dev \
        libyaml-cpp-dev \
        python3-pip \
        jq \
        inotify-tools \
        lsof \
        net-tools \
        iputils-ping \
        vim \
        netcat \
        iptables \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN mkdir /app
## install from source with debug flag on
COPY precice-2.5.0 /app/precice-2.5.0
WORKDIR /app/precice-2.5.0/build
RUN rm -rf *
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DPRECICE_RELEASE_WITH_DEBUG_LOG=ON ..
RUN make clean
RUN make
RUN make install
RUN make test_install

## install adapter
WORKDIR /app
RUN wget http://www.dhondt.de/ccx_2.20.src.tar.bz2
RUN tar xvjf ccx_2.20.src.tar.bz2  
# The source code is now in the /app/CalculiX/ccx_2.20/src directory where the adapter is looking for it (set in Makefile)
# install adapter from source too required
COPY calculix-adapter-master /app/calculix-adapter-master
WORKDIR /app/calculix-adapter-master
RUN make clean
RUN make
WORKDIR /usr/local/bin
RUN ln -s /app/calculix-adapter-master/bin/ccx_preCICE ccx_preCICE

### ask the dynamic linker to check /usr/local/lib too (required so that adapter can find precice)
RUN echo "/usr/local/lib" >> /etc/ld.so.conf
RUN ldconfig

# setup component folders
COPY protobufs /app/protobufs
COPY generic-python3-comp/editables /app/precice-calculix-comp/editables
COPY generic-python3-comp/precice-comp/precice.py /app/precice-calculix-comp/
COPY generic-python3-comp/precice-comp/tools /app/precice-calculix-comp/tools
COPY generic-python3-comp/calculix-fea-comp/calculix.py /app/precice-calculix-comp/
COPY generic-python3-comp/component.py /app/precice-calculix-comp/
COPY generic-python3-comp/component_api.py /app/precice-calculix-comp/
COPY generic-python3-comp/requirements.txt /app/precice-calculix-comp/
COPY generic-python3-comp/README.md /app/precice-calculix-comp/
COPY generic-python3-comp/VERSION /app/precice-calculix-comp/
COPY generic-python3-comp/LICENSE /app/precice-calculix-comp/

RUN chmod -R 755 /app
WORKDIR /app/precice-calculix-comp

RUN chmod -R 777 editables

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
RUN python -m grpc_tools.protoc -I ../protobufs --python_out=. --grpc_python_out=. ../protobufs/component.proto

# set non-root user (already created in precice ci image)
# ARG USERNAME=precice
# USER $USERNAME

EXPOSE 50060
ENTRYPOINT ["python", "-u", "component_api.py" ]